---
seed: 42
logging:
  project: "play_segmentation"
  model_directory: "../../model_store"
  experiment_name: "imitation_learning_babyai"
  mode: online
  tags: ["BabyAI","Imitation Learning"]

data:
  env_name: "go_to"
  dataset_directory: "../../datasets/babyai"
  dataset: "babyai"
  dataset_file: ""
  use_state: True
  batch_size: 256
  num_workers: 4
  instruction_embeddings:
    type: t5
    model: "google-t5/t5-small"

trainer:
  lr: 0.0001
  model:
    action_space: 7
    instruction_dim: 512
    policy:
      mlp:
        hidden_dim: 1024
        num_layers: 3

  load:
    load: False
    experiment_name: "imitation_learning_babyai"
    run_id: ""
    checkpoint: ""

training:
  distributed: True
  accelerator: "gpu"
  gpus: [0]
  max_steps: 20000
  val_check_interval: 1000
  strategy: "ddp_find_unused_parameters_true"

evaluation:
  env_name: go_to
  use_state: True
  seed: 42
  max_timesteps: 25
  num_envs: 512
  n_iterations: 1
  render: True
  embedding_config:
    path: "../../datasets/babyai/embeddings_go_to_t5.pkl"
    tokenizer: "google-t5/t5-small"
    model: "google-t5/t5-small"
