---
algorithm: i3d
logging:
  experiment_name: "labelling_model_babyai"
  mode: online
  project: play_segmentation
  tags: ["ID3","BabyAI","Labelling Model"]
  model_directory: ../../../../model_store

data:
  env: babyai
  env_name: go_to
  debug: True
  dataset_directory: "../../../datasets/babyai"
  train_ratio: 0.8
  batch_size: 256
  num_workers: 5
  filename: "babyai_go_to_10000_single"

trainer:
  lr: 0.0001
  gamma: 2

  model:
    temp_kernels: [[5],[3],[3,1],[3,1],[1,3]]
    num_blocks: [3, 4, 6, 3]
    num_blocks_temporal_kernel: [3, 4, 6, 3]
    channels: [64,256,512,1024,2048]
    input_channel: 3
    inner_channels: 64
    spatial_strides: [1, 2, 2, 2]
    spatial_dilations: [1, 1, 1, 1]
    nonlocal:
      location: [[],[],[],[]]
    num_classes: 36
    dropout: 0.5

  load:
    load: False
    checkpoint: ""
    experiment_name: ""

training:
  distributed: True
  epochs: 250
  gpus: [0]
  accelerator: "gpu"
  strategy: 'ddp'
  precision: 32
  accumulate_grad_batches: 1
