---
thresholds: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
logging:
  experiment_name: "play_segmentation_calvin_accuracy_confidence"
  mode: online
  project: play_segmentation
  tags: ["PlaySegmentation","CALVIN", "Accuracy_Confidence"]
  model_directory: ../../model_store

data:
  env: calvin
  debug: False
  dataset_directory: "../../datasets/calvin/task_D_D"
  buffer: 5
  max_distance: 15
  batch_size: 4
  num_workers: 2
  episode_filename: "auto_lang_ann_25.npy"
