---
algorithm: play_segmentation
seed: 1

logging:
  experiment_name: "play_segmentation_babyai_training"
  mode: online
  project: play_segmentation
  tags: ["PlaySegmentation","BabyAI","Training"]
  model_directory: ../../model_store

data:
  env: babyai
  env_name: go_to
  debug: False
  dataset_directory: "../../datasets/babyai"
  buffer: 1
  max_distance: 5
  batch_size: 128
  num_workers: 2
  filename: "babyai_go_to_10000_unsegmented"

trainer:
  lr: 0.00005
  model:
    env: "babyai"
    num_classes: 36
    use_language: False
    obs_dim: 2048
    architecture: "convolution"
    conv:
      n_layers: 2
      context_length: 11
    transformer:
      d_dim: 1024
      n_head: 8
      hidden_dim: 1024
      num_layers: 1
      dropout: 0
      context_length: -1
      use_positional_encoding: False
    i3d:
      use: True
  load:
    load: False
    checkpoint: ""
    experiment_name: ""
    data_parallel: True # Was data parallel used during training

training:
  distributed: True
  epochs: 250
  gpus: [0]
  accelerator: "gpu"
  strategy: 'ddp_find_unused_parameters_true'
  evaluation_frequency: 1
