---
device: "cuda:0"

# Directories
visualizations_directory: "../../../visualisations/labelled_segmentation/babyai"
model_directory: "../../../model_store"
dataset_directory: "../../../datasets/babyai"

# Data
env: "babyai"
env_name: go_to
dataset_file: "babyai_go_to_100000_unsegmented_training.pkl"
labelled_dataset_file: "babyai_go_to_10000_single_training.pkl"

# Hyperparameters
n_labelled_segments: 90000
tridet_segment_size: 32
n_visualisations: 20

logging:
  project: "play_segmentation"
  mode: online
  tags: ["Labelled_Segmentation", "TriDet", "BabyAI"]
  experiment_name: "labelling_tridet_babyai"
